# Name: Jayveersinh Raj
# Group: BS20-DS-01
# Email: j.raj@innopolis.university

In [27]:
# Importing Dependencies
import pandas as pd
import numpy as np

# Reading from CSV file

In [28]:
df = pd.read_excel("/content/NIC GA matrix.xlsx")
df.reset_index(drop = True)

ID    Unnamed: 1                                                1.0  \
0      NaN          name                                                 SM   
1      1.0            SM                                                0.0   
2      2.0            ST                                                9.0   
3      3.0            DG                                                9.0   
4      4.0            HC                                                9.0   
5      9.0            PS                                                9.0   
6     10.0           ICT                                                9.0   
7     13.0           CSP                                                9.0   
8     16.0            VM                                                9.0   
9     22.0           CMS                                                9.0   
10    26.0            GS                                                9.0   
11     NaN           NaN                                                NaN   
12     NaN           NaN                                                NaN   
13     NaN           NaN                                                NaN   
14    3 hr           9.0               Allergens - Wet Cleaning is required   
15    1 hr           3.0  Different Flavor/color / odor - Dry Cleaning w...   
16  20 min           1.0  Similar recipes - Scraping of previous batch r...   
17     NaN           0.0                    Same Mix - No need for cleaning   
18     NaN           NaN                                                NaN   
19     NaN           NaN                                                NaN   
20      ID  Total Demand                                                NaN   
21    10.0          30.0                                                NaN   
22     2.0           7.0                                                NaN   
23     1.0           7.0                                                NaN   
24    22.0          10.0                                                NaN   
25    26.0          65.0                                                NaN   
26     3.0          67.0                                                NaN   
27    13.0          20.0                                                NaN   
28     4.0           4.0                                                NaN   
29     9.0          10.0                                                NaN   
30    16.0          60.0                                                NaN   

    2.0  3.0  4.0  9.0 10.0 13.0 16.0 22.0 26.0  
0    ST   DG   HC   PS  ICT  CSP   VM  CMS   GS  
1   1.0  1.0  3.0  1.0  3.0  3.0  3.0  3.0  1.0  
2   0.0  1.0  3.0  9.0  3.0  3.0  3.0  3.0  1.0  
3   3.0  0.0  3.0  9.0  3.0  3.0  3.0  3.0  1.0  
4   9.0  9.0  0.0  9.0  3.0  3.0  9.0  3.0  9.0  
5   9.0  9.0  1.0  0.0  1.0  9.0  9.0  9.0  9.0  
6   9.0  9.0  1.0  9.0  0.0  9.0  9.0  9.0  9.0  
7   9.0  9.0  1.0  9.0  1.0  0.0  9.0  3.0  9.0  
8   1.0  1.0  1.0  9.0  3.0  1.0  0.0  3.0  1.0  
9   9.0  9.0  3.0  3.0  3.0  3.0  9.0  0.0  9.0  
10  3.0  3.0  3.0  9.0  3.0  3.0  3.0  3.0  0.0  
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
12  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
13  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
14  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
15  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
16  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
17  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
18  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
19  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
20  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
21  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
22  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
23  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
24  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
25  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
26  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
27  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
28  NaN  NaN  NaN  NaN  NaN  

# Getting relevant data in different DataFrames

In [29]:
df_matrix = df.iloc[:11,:]
df_time = df.iloc[14:18,0:3]
df_need = df.iloc[21:,0:2]

In [30]:
df_time

ID Unnamed: 1                                                1.0
14    3 hr        9.0               Allergens - Wet Cleaning is required
15    1 hr        3.0  Different Flavor/color / odor - Dry Cleaning w...
16  20 min        1.0  Similar recipes - Scraping of previous batch r...
17     NaN        0.0                    Same Mix - No need for cleaning

# Storing IDs in a separate array

In [31]:
ids = df_matrix['ID'].iloc[1:]
df_matrix = df_matrix.drop(['ID'], axis = 1)
ids = np.array(ids)
ids

array([1.0, 2.0, 3.0, 4.0, 9.0, 10.0, 13.0, 16.0, 22.0, 26.0],
      dtype=object)

# Storing names in a separate array

In [32]:
names = df_matrix.iloc[1:,0]
df_matrix = df_matrix.drop(['Unnamed: 1'], axis = 1)
names = np.array(names)
names

array(['SM', 'ST', 'DG', 'HC', 'PS', 'ICT', 'CSP', 'VM', 'CMS', 'GS'],
      dtype=object)

# Getting only the relevant matrix from the DataFrame

In [33]:
matrix = df_matrix.iloc[1:,:]
matrix = np.array(matrix)
matrix

array([[0.0, 1.0, 1.0, 3.0, 1.0, 3.0, 3.0, 3.0, 3.0, 1.0],
       [9.0, 0.0, 1.0, 3.0, 9.0, 3.0, 3.0, 3.0, 3.0, 1.0],
       [9.0, 3.0, 0.0, 3.0, 9.0, 3.0, 3.0, 3.0, 3.0, 1.0],
       [9.0, 9.0, 9.0, 0.0, 9.0, 3.0, 3.0, 9.0, 3.0, 9.0],
       [9.0, 9.0, 9.0, 1.0, 0.0, 1.0, 9.0, 9.0, 9.0, 9.0],
       [9.0, 9.0, 9.0, 1.0, 9.0, 0.0, 9.0, 9.0, 9.0, 9.0],
       [9.0, 9.0, 9.0, 1.0, 9.0, 1.0, 0.0, 9.0, 3.0, 9.0],
       [9.0, 1.0, 1.0, 1.0, 9.0, 3.0, 1.0, 0.0, 3.0, 1.0],
       [9.0, 9.0, 9.0, 3.0, 3.0, 3.0, 3.0, 9.0, 0.0, 9.0],
       [9.0, 3.0, 3.0, 3.0, 9.0, 3.0, 3.0, 3.0, 3.0, 0.0]], dtype=object)

In [34]:
df_need['need'] = df_need['Unnamed: 1']
df_need = df_need.drop(['Unnamed: 1'], axis = 1)
df_need

ID  need
21  10.0  30.0
22   2.0   7.0
23   1.0   7.0
24  22.0  10.0
25  26.0  65.0
26   3.0  67.0
27  13.0  20.0
28   4.0   4.0
29   9.0  10.0
30  16.0  60.0

In [35]:
df_need['ID'] = pd.to_numeric(df_need['ID'])

In [36]:
df_need = df_need.sort_values(by=['ID'])

# Ids with their respective needs (sorted ascending)

In [37]:
df_need

ID  need
23   1.0   7.0
22   2.0   7.0
26   3.0  67.0
28   4.0   4.0
29   9.0  10.0
21  10.0  30.0
27  13.0  20.0
30  16.0  60.0
24  22.0  10.0
25  26.0  65.0

# The sorted need array, sorted it to make it easy for below implemented mapped ids to calculate score, and map themselves back to original ids

In [38]:
df_need['need'] = pd.to_numeric(df_need['need'])
df_need['need'] = df_need['need'].astype('int')
need = df_need['need']
need = np.array(need)
need

array([ 7,  7, 67,  4, 10, 30, 20, 60, 10, 65])

# The below code cell contains mapped ids, as the ids are not consitant numbers, we map them to numebrs from 0 to the total ids
## Reason : It would help `fitness` function check the indexes of need and weight matrix to calculate score

In [39]:
ids_mapped = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# The weight matrix that determines time taken for washing

In [40]:
matrix

array([[0.0, 1.0, 1.0, 3.0, 1.0, 3.0, 3.0, 3.0, 3.0, 1.0],
       [9.0, 0.0, 1.0, 3.0, 9.0, 3.0, 3.0, 3.0, 3.0, 1.0],
       [9.0, 3.0, 0.0, 3.0, 9.0, 3.0, 3.0, 3.0, 3.0, 1.0],
       [9.0, 9.0, 9.0, 0.0, 9.0, 3.0, 3.0, 9.0, 3.0, 9.0],
       [9.0, 9.0, 9.0, 1.0, 0.0, 1.0, 9.0, 9.0, 9.0, 9.0],
       [9.0, 9.0, 9.0, 1.0, 9.0, 0.0, 9.0, 9.0, 9.0, 9.0],
       [9.0, 9.0, 9.0, 1.0, 9.0, 1.0, 0.0, 9.0, 3.0, 9.0],
       [9.0, 1.0, 1.0, 1.0, 9.0, 3.0, 1.0, 0.0, 3.0, 1.0],
       [9.0, 9.0, 9.0, 3.0, 3.0, 3.0, 3.0, 9.0, 0.0, 9.0],
       [9.0, 3.0, 3.0, 3.0, 9.0, 3.0, 3.0, 3.0, 3.0, 0.0]], dtype=object)

# Individual -> Schedule containing unique ids
# genes -> the unique ids.

# A list to store the best_schedule generated

In [41]:
best_schedule = []

# `GeneticAlgorithm` class that implements all the methods of a genetic algorithm
## Description of methods:
* ## *`populate`:* Generates initial population with schedule (containing unique ids) as individuals
* ## *`fitness`:* Calculates the fitness of an individual.
     ## It looks up in the sorted `need` dataframe and multiplies it by 20, and adds up the time it takes to create spice of the other id. 
     * ## Since all takes 20 minutes, no production can exceed 20 hr/day (1200 min/hr) limit, and if the productio of that particular id is not finished, it could start next day. 
     * ## If cleaning was the last thing happening while 20hr were completed, fitness function still penalise that individual with time taken for cleaning, and production of that particular spice can start next day.
*## *`select`:* A method to select/choose elite individuals. It calls an `accept method` that generates a random number in range [1-100], and gets `normalized` scores from `select method`, which in turns gets it from `ga_loop` function that is `responsible for handling genetic loop, normalising score, and giving the result`. An individual is selected randomly, if that individual's normalised score is greater than the produced random number we accept it. (That is to say that since `score` is time taken, and we need to minimize it. If an indvidual with score 10 is picked, take it 90% of the time). 
*## *`mutation`*: A method that implements mutation in genetic algorithm. It swaps two unique ids position inside the gene of an individual. The number of time it does this is based on the hyperparameter that accepts it as probability or percentage. This method generates a number between [1-100], multiplies the given hypermeter with 100 if probability is passed, and if the generated number is less than or equal to the hyper parameter it muatates it i.e. swaps the ids.


In [42]:
from random import randint

# class with methods of the entire genetic algorithm loop
class GeneticAlgorithm:

    def __init__(self) -> None:
        pass

   # function to populate the population
    def populate(target_len,n) -> list:

    # empty list to store our initial population
      population = []
       
      # Size of population is n with size equal to the target
      for _ in range(n):
        # list to store the paths as individual
        individual = []
        # each element in population is a parent for future generations
        for _ in range(target_len):
          notUnique = True
          while notUnique:
            ran_value = randint(0, 9)
            if ran_value in individual:
              ran_value = randint(0, 9)
            else:
              notUnique = False
          individual.append(ran_value)
        # once the loop ends we have a parent  
        population.append(individual)
       
      return population


# function to calculate fitness
    def fitness(matrix, individual, sum) -> tuple:
      # list of taken time according to csv (in minutes)
      time_taken = [0, 20, 60, 180] 
      # list of id according to cleaning mechanism (the unique values in matrix)
      list_cleaning = [0, 1, 3, 9]

      # fitness score of inidividual
      score = 0

      # for each character if they are the same and in the correct position
      for i in range(len(individual)-1):
        cleaning = matrix[individual[i]][individual[i+1]]
        cleaning = int(cleaning)
        if(int(cleaning) == 3):
          cleaning = 2
        if(int(cleaning) == 9):
          cleaning = 3

        score += need[individual[i]]*20 + time_taken[cleaning]
       
      if(score<sum):
            sum = score
            
      return (score,sum)



    # function to create a mating pool for cross over by populating parents according to their fitting
    @classmethod
    def select(cls, population, scores, max_score) -> list:
      parents_to_breed = []
      # scores in integer values
      p1 = cls.accept(population,scores, max_score)
      p2 = cls.accept(population, scores, max_score)
      parents_to_breed.append(p1)
      parents_to_breed.append(p2)
            
      return parents_to_breed


    # check the probabilities of generated parent meets the criteria with random number probability
    def accept(population, scores, max_score) -> list:
      while True:
        parent_index = randint(0, len(population)-1)
        rand_num = randint(0,max_score)

        # since we want to minimize, we take the individual with low scores (weights/distances) 1-probability rule
        if(rand_num > scores[parent_index]):
          return population[parent_index]
        else:
          pass 


    # function for crossover
    def crossover(parent1, parent2, split_point) -> list:
      p1 = parent1.copy()
      p2 = parent2.copy()
      child = []
      if(split_point == 0):
        child = p2
      elif(split_point == len(p1)-1):
        child = p1
      else:
        for i in p1[:split_point]:
          child.append(i)
        for j in p2:
            if j in child:
              pass
            else:
              child.append(j)
          
      return child



    # function for mutation
    def mutate(individual, chance) -> list:
     
      # if chance is not provided as percentage, multiply by 100
      if(chance<=1):
         chance = chance * 100
      else:
          pass
      
      # according to given mutation chance change characters/genes of an individual
      for i in range(len(individual)):
           mutation_genes = randint(0, 100)

           if (mutation_genes <= chance):
             same = True
             while same:
               ran_value = randint(0, len(individual)-1)
               if(individual[i] != individual[ran_value]):
                 individual[i], individual[ran_value] = individual[ran_value], individual[i]
                 same = False
               else:
                pass

      return individual



# The main loop that performs the loop of genetic algorithm by calling the methods recursively, and returns the result

In [43]:
from random import randint
import math

# to store number of generation
generation = 1
# to store the total distance (by default infinity)
sum = math.inf
# to early stop
dropout_counter = 0
# to store the best solution we have on a given generation
best_so_far = []


def ga_loop(dist, population, mutation_probability,dropout,n_generations) -> tuple: 

    global generation
    global sum
    global best_so_far
    global dropout_counter

    # to stop on a particular epoch/generation
    if(generation == n_generations):
        return (sum, best_so_far)
    
    # incrementing generation
    generation += 1
    
    # if not getting better solution for a particular number of epochs, early stop, and return the best so far
    if(dropout[0] == True and dropout_counter == dropout[1]):
        print("\n dropped out, Early stopping...!!!")
        return (sum, best_so_far)
    
    # scores from fitting function
    scores = []
   
    # for every individual in the population find fitness, and get the (score, sum)
    for p in population:
        fitness = GeneticAlgorithm.fitness(dist, p, sum)
        scores.append(fitness[0])

        # if the found score is less than any previous best, replace it
        if(fitness[1]<sum):
          global best_schedule
          best_schedule = p
          sum = fitness[1]

          dropout_counter = 0

    dropout_counter+=1
    
    min_score = min(scores)
    max_score = max(scores)
       
    # normalizing the scores
    int_scores = [((score-min_score)/max_score) for score in scores]
    
    # getting them to double precision
    int_scores = [ '%.2f' % elem for elem in int_scores]

    # calculating them as percentage
    percnt_scores = [int(float(score)*100) for score in int_scores]
    
    # just a little fanciness for output
    bar = '█'*(int((generation/n_generations)*100)) + '-' *(100 - int((generation/n_generations)*100))
    print(f"\r|{bar}| {int(generation/n_generations*100)}%", end = "\r")

    max_score = max(percnt_scores)
 
    # new population from mating pool
    new_population = []
   
    # selecting the parents, crossing over, and mutation based on given mutation chance
    for _ in range(len(population)):

        # creating a mating pool of elements using their probabilities from fitting 
        mating_parents = GeneticAlgorithm.select(population, percnt_scores, max_score)       
        
         # split from random points
        split_point = randint(0, len(mating_parents[0])-1)        

        # crossover of those parents to yield a breed
        breed = GeneticAlgorithm.crossover(mating_parents[0], mating_parents[1], split_point)      
        
        # mutating the produced breed and adding it to the population
        new_population.append(GeneticAlgorithm.mutate(breed, mutation_probability))  
  
    # Repeat by calculating the fitness
    return ga_loop(dist, new_population, mutation_probability, dropout, n_generations)

# Below is the main driver code cell
# * *`hyper_parameter`* dictionary contains hyper parameters

##🔑 NOTE:  *`dropout`* is the name given for `early stopping` hyper parameter

In [44]:
import time

hyper_parameter = {
    # size of population
    "population_size": 500,
    
    # mutation percentage
    "mutation_per": 0.01,

    # early stop for the generations till which no better solution found
    "dropout": False,

    "dropout_number": 0,
    
    # number of epochs
    "n_generations": 100
}

t = time.time()
# Populate
population = GeneticAlgorithm.populate(len(ids_mapped), hyper_parameter['population_size'])
## main ga(genetic algorithm) loop to find the result
result = ga_loop(matrix, population, hyper_parameter['mutation_per'], 
                 (hyper_parameter['dropout'], hyper_parameter['dropout_number']), 
                 hyper_parameter['n_generations'])
best_result = []
for b in best_schedule:
  best_result.append(int(ids[b]))

print(f"\n\n* The best schedule should be according to the following ids: ")
print(f"\n   {best_result}")

print(f"\n\n* Above order of production can be completed in the following minutes: ")
print(f"\n   {result[0]} minutes")

print(f"\n\nTime saved : {8400 - result[0]} minutes")

|████████████████████████████████████████████████████████████████████████████████████████████████████| 100%

* The best schedule should be according to the following ids: 

   [1, 9, 4, 22, 13, 10, 2, 26, 16, 3]


* Above order of production can be completed in the following minutes: 

   4720 minutes


Time saved : 3680 minutes
